Revert "[install-deps-worker.yaml] install marshmallow-3"
This reverts commit 75d468630b2e399a83c4ba06601cc29e32d13905.

Fixes:
/usr/lib/python3.7/site-packages/copr/client_v2/entities.py:45: in ProjectEntity
    _schema = ProjectSchema(strict=True)
E   TypeError: __init__() got an unexpected keyword argument 'strict'