Make the static methods in Parser.MAPPING callable
Static methods have been callable as regular functions since 3.10
https://docs.python.org/3/library/functions.html#staticmethod

For 3.9 (c9s) we access the underlying function direcly with the __func__ attribute
https://stackoverflow.com/a/41921291/2768738

The 'type: ignore' is for mypy to avoid
error: "Callable" has no attribute "__func__"  [attr-defined]